import Head from "next/head";
import { Header } from "../componets/Header";
import { Main } from "../componets/Main";
import { Footer } from "../componets/Footer";
import { Headline } from "../componets/Headline";

import { Inter } from "@next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Headline
        page="about"
        number={111}
        array={[1, 2, 3]}
        obj={{ foo: "foo", bar: "bar" }}
        boolean={true}
      />
      <Main page="index page" />
      <Footer />
    </>
  );
}
